"""
Execution engine for the sieveon Memory Control Plane
Executes the plans generated by the planner using various retrieval strategies
"""

import asyncio
import logging
import os
import re
import sys
import time
from enum import Enum
from typing import Any, Dict, List, Optional

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from ..extraction.entropy_gate import escape_surrealql
from ..mcp.core import _clean_output, _extract_result, _query_surreal
from ..router.cost_awareness import cost_tracker
from ..router.policy import BudgetLevel, QueryType


class RetrievalStrategy(Enum):
    """Available retrieval strategies"""

    EVENT_LOG_FIRST = "event_log_first"
    KNOWLEDGE_GRAPH_FIRST = "knowledge_graph_first"
    HYBRID_WITH_GRAPH_EXPANSION = "hybrid_with_graph_expansion"
    COMPOSITE_KG_VECTOR = "composite_kg_vector"
    KNOWLEDGE_GRAPH_WITH_INVALIDATION = "knowledge_graph_with_invalidation"
    HYBRID_BM25_VECTOR_TEMPORAL = "hybrid_bm25_vector_temporal"
    HYBRID_FALLBACK = "hybrid_fallback"
    SEMANTIC_HYBRID = "semantic_hybrid"


class BudgetTracker:
    """Tracks resource consumption for a single execution"""

    def __init__(self, budget_level: BudgetLevel):
        self.db_calls = 0
        self.estimated_tokens = 0
        self.budget_level = budget_level

        # Budget limits per level
        self.limits = {
            BudgetLevel.LOW: {"db_calls": 10, "tokens": 1000},
            BudgetLevel.MEDIUM: {"db_calls": 25, "tokens": 3000},
            BudgetLevel.HIGH: {"db_calls": 50, "tokens": 8000},
        }

    def increment_db_calls(self, count: int = 1):
        self.db_calls += count

    def increment_tokens(self, count: int):
        self.estimated_tokens += count

    def is_over_budget(self) -> bool:
        limits = self.limits[self.budget_level]
        return (
            self.db_calls > limits["db_calls"]
            or self.estimated_tokens > limits["tokens"]
        )

    def get_remaining_budget(self) -> Dict[str, int]:
        limits = self.limits[self.budget_level]
        return {
            "remaining_db_calls": max(0, limits["db_calls"] - self.db_calls),
            "remaining_tokens": max(0, limits["tokens"] - self.estimated_tokens),
        }


class RetrievalExecutor:
    """Executes retrieval operations using different strategies"""

    def __init__(self):
        self.db_connection = None
        self.budget_enforcement = True

    async def execute_strategy(
        self,
        strategy: RetrievalStrategy,
        query: str,
        budget_tracker: BudgetTracker,
        **kwargs,
    ) -> Dict[str, Any]:
        """
        Execute a retrieval strategy with budget enforcement and cost tracking.
        """
        start_time = time.time()
        success = True
        num_queries = 0
        relevance_score = 0.5

        try:
            if budget_tracker.is_over_budget():
                raise Exception("Over budget")

            if strategy == RetrievalStrategy.EVENT_LOG_FIRST:
                result = await self._execute_event_log_first(
                    query, budget_tracker, **kwargs
                )
                num_queries += 1
            elif strategy == RetrievalStrategy.KNOWLEDGE_GRAPH_FIRST:
                result = await self._execute_knowledge_graph_first(
                    query, budget_tracker, **kwargs
                )
                num_queries += 1
            elif strategy == RetrievalStrategy.HYBRID_WITH_GRAPH_EXPANSION:
                result = await self._execute_hybrid_with_graph_expansion(
                    query, budget_tracker, **kwargs
                )
                num_queries += 2
            elif strategy == RetrievalStrategy.COMPOSITE_KG_VECTOR:
                result = await self._execute_composite_kg_vector(
                    query, budget_tracker, **kwargs
                )
                num_queries += 2
            elif strategy == RetrievalStrategy.KNOWLEDGE_GRAPH_WITH_INVALIDATION:
                result = await self._execute_knowledge_graph_with_invalidation(
                    query, budget_tracker, **kwargs
                )
                num_queries += 2
            elif strategy == RetrievalStrategy.HYBRID_BM25_VECTOR_TEMPORAL:
                result = await self._execute_hybrid_bm25_vector_temporal(
                    query, budget_tracker, **kwargs
                )
                num_queries += 2
            elif strategy == RetrievalStrategy.HYBRID_FALLBACK:
                result = await self._execute_hybrid_fallback(
                    query, budget_tracker, **kwargs
                )
                num_queries += 1
            elif strategy == RetrievalStrategy.SEMANTIC_HYBRID:
                result = await self._execute_semantic_hybrid(
                    query, budget_tracker, **kwargs
                )
                num_queries += 2
            else:
                raise ValueError(f"Unknown strategy: {strategy}")

            relevance_score = self._calculate_relevance_score(result, query)

        except Exception as e:
            success = False
            logging.error(f"Strategy {strategy.value} failed: {e}")
            result = {"error": str(e), "events": [], "entities": [], "facts": []}

        finally:
            end_time = time.time()
            latency = end_time - start_time

            cost_tracker.record_request(
                strategy=strategy.value,
                latency=latency,
                success=success,
                num_queries=num_queries,
                relevance=relevance_score,
            )

        return result

    def _calculate_relevance_score(self, result: Dict[str, Any], query: str) -> float:
        """Calculate a relevance score based on the result quality."""
        if "error" in result:
            return 0.1

        total = 0
        for key in ("events", "entities", "facts"):
            total += len(result.get(key, []))

        if total == 0:
            return 0.2

        relevance = min(0.9, 0.3 + (total * 0.1))

        query_lower = query.lower()
        if any(word in query_lower for word in ["who", "what", "where"]) and total > 0:
            relevance = min(1.0, relevance + 0.1)

        return relevance

    async def _search_events_ftx(self, query: str, limit: int = 10) -> List[Dict]:
        """Lexical search via FTX index."""
        query_escaped = escape_surrealql(query)
        forgotten_filter = "(forgotten IS NONE OR forgotten = false)"
        sql = f"""
        SELECT id, content, timestamp, source, metadata
        FROM event
        WHERE content @@ '{query_escaped}'
          AND {forgotten_filter}
        LIMIT {limit * 4};
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_events_vector(self, query: str, limit: int = 10) -> List[Dict]:
        """Semantic search via vector similarity."""
        from src.mcp.core import _embed_query

        query_vector = await _embed_query(query)
        query_vector_str = "[" + ", ".join(map(str, query_vector)) + "]"
        forgotten_filter = "(forgotten IS NONE OR forgotten = false)"
        sql = f"""
        SELECT id, content, timestamp, source, metadata,
               vector::similarity::cosine(embedding, {query_vector_str}) AS vec_score
        FROM event
        WHERE embedding IS NOT NONE
          AND {forgotten_filter}
          AND array::len(embedding) = {len(query_vector)}
        ORDER BY vec_score DESC
        LIMIT {limit * 4};
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_events_temporal(self, query: str, limit: int = 10) -> List[Dict]:
        """Temporal search (recent events)."""
        forgotten_filter = "(forgotten IS NONE OR forgotten = false)"
        sql = f"""
        SELECT id, content, timestamp, source, metadata
        FROM event
        WHERE {forgotten_filter}
        ORDER BY timestamp DESC
        LIMIT {limit};
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_kg_by_subject(self, subject: str) -> List[Dict]:
        """Search knowledge graph by subject name."""
        subject_escaped = escape_surrealql(subject)
        sql = f"""
        SELECT id, in, out, predicate, confidence, valid_from, valid_until
        FROM fact
        WHERE in.name = '{subject_escaped}'
        ORDER BY confidence DESC
        LIMIT 50;
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_kg_by_text(self, text: str) -> List[Dict]:
        """Search knowledge graph by matching predicate or entity names."""
        text_escaped = escape_surrealql(text)
        sql = f"""
        SELECT id, in, out, predicate, confidence, valid_from, valid_until
        FROM fact
        WHERE predicate CONTAINS '{text_escaped}'
           OR in.name CONTAINS '{text_escaped}'
           OR out.name CONTAINS '{text_escaped}'
        ORDER BY confidence DESC
        LIMIT 50;
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_entities_by_name(self, name: str) -> List[Dict]:
        """Search entities by name (substring match via CONTAINS)."""
        name_escaped = escape_surrealql(name)
        sql = f"""
        SELECT id, name, type
        FROM entity
        WHERE name CONTAINS '{name_escaped}'
        LIMIT 20;
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _execute_event_log_first(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute event log first strategy — search events via FTX + temporal."""
        budget_tracker.increment_db_calls(2)
        budget_tracker.increment_tokens(len(query) // 4)

        ftx_events, temporal_events = await asyncio.gather(
            self._search_events_ftx(query, 10), self._search_events_temporal(query, 5)
        )

        # RRF fusion
        k = 60
        seen_ids = set()
        fused = []
        for rank, ev in enumerate(ftx_events):
            eid = ev.get("id")
            if eid and eid not in seen_ids:
                seen_ids.add(eid)
                ev["_rrf_score"] = 1.0 / (k + rank)
                fused.append(ev)
        for rank, ev in enumerate(temporal_events):
            eid = ev.get("id")
            if eid and eid not in seen_ids:
                seen_ids.add(eid)
                ev["_rrf_score"] = 1.0 / (k + len(ftx_events) + rank)
                fused.append(ev)

        fused.sort(key=lambda x: x.get("_rrf_score", 0), reverse=True)
        for ev in fused:
            ev.pop("_rrf_score", None)

        return {
            "strategy": "event_log_first",
            "events": _clean_output(fused[:10]),
            "entities": [],
            "facts": [],
            "query": query,
        }

    async def _execute_knowledge_graph_first(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute knowledge graph first strategy — search KG + entities."""
        budget_tracker.increment_db_calls(3)
        budget_tracker.increment_tokens(len(query) // 4)

        # Extract potential subject words from query (simple heuristic)
        words = query.split()
        subjects_to_try = []
        for w in words:
            w_clean = w.strip(",.!?;:")
            if w_clean and w_clean[0].isupper():
                subjects_to_try.append(w_clean)
        if not subjects_to_try:
            subjects_to_try = [query]

        # Search entities and KG in parallel
        entity_tasks = [self._search_entities_by_name(s) for s in subjects_to_try[:3]]
        kg_tasks = [self._search_kg_by_text(query)]

        all_results = await asyncio.gather(*(entity_tasks + kg_tasks))

        entities = []
        seen_entity_ids = set()
        for r in all_results[: len(entity_tasks)]:
            for e in r:
                eid = e.get("id")
                if eid and eid not in seen_entity_ids:
                    seen_entity_ids.add(eid)
                    entities.append(e)

        facts = []
        seen_fact_ids = set()
        for r in all_results[len(entity_tasks) :]:
            for f in r:
                fid = f.get("id")
                if fid and fid not in seen_fact_ids:
                    seen_fact_ids.add(fid)
                    facts.append(f)

        return {
            "strategy": "knowledge_graph_first",
            "events": [],
            "entities": _clean_output(entities),
            "facts": _clean_output(facts),
            "query": query,
        }

    async def _execute_hybrid_with_graph_expansion(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute hybrid with graph expansion — events + KG + entity expansion."""
        budget_tracker.increment_db_calls(4)
        budget_tracker.increment_tokens(len(query) // 3)

        ftx_events, kg_facts, entities = await asyncio.gather(
            self._search_events_ftx(query, 10),
            self._search_kg_by_text(query),
            self._search_entities_by_name(query),
        )

        # Expand: for each found entity, get related facts
        expanded_facts = list(kg_facts)
        seen_fact_ids = {f.get("id") for f in kg_facts if f.get("id")}
        for ent in entities[:5]:
            ent_name = ent.get("name", "")
            if ent_name:
                more_facts = await self._search_kg_by_subject(ent_name)
                for f in more_facts:
                    fid = f.get("id")
                    if fid and fid not in seen_fact_ids:
                        seen_fact_ids.add(fid)
                        expanded_facts.append(f)

        return {
            "strategy": "hybrid_with_graph_expansion",
            "events": _clean_output(ftx_events),
            "entities": _clean_output(entities),
            "facts": _clean_output(expanded_facts),
            "query": query,
        }

    async def _execute_composite_kg_vector(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute composite KG-vector strategy — KG facts + vector search on events."""
        budget_tracker.increment_db_calls(3)
        budget_tracker.increment_tokens(len(query) // 3)

        kg_facts, entities, ftx_events = await asyncio.gather(
            self._search_kg_by_text(query),
            self._search_entities_by_name(query),
            self._search_events_ftx(query, 10),
        )

        return {
            "strategy": "composite_kg_vector",
            "events": _clean_output(ftx_events),
            "entities": _clean_output(entities),
            "facts": _clean_output(kg_facts),
            "query": query,
        }

    async def _execute_knowledge_graph_with_invalidation(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute knowledge graph with invalidation — search KG + check for stale facts."""
        budget_tracker.increment_db_calls(3)
        budget_tracker.increment_tokens(len(query) // 4)

        kg_facts, entities = await asyncio.gather(
            self._search_kg_by_text(query), self._search_entities_by_name(query)
        )

        # Check for invalidated (stale) facts among results
        stale_facts = [f for f in kg_facts if f.get("valid_until") is not None]
        active_facts = [f for f in kg_facts if f.get("valid_until") is None]

        return {
            "strategy": "knowledge_graph_with_invalidation",
            "events": [],
            "entities": _clean_output(entities),
            "facts": _clean_output(active_facts),
            "stale_facts": _clean_output(stale_facts),
            "query": query,
        }

    async def _execute_hybrid_bm25_vector_temporal(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute hybrid BM25-vector-temporal — full event search + KG."""
        budget_tracker.increment_db_calls(4)
        budget_tracker.increment_tokens(len(query) // 3)

        ftx_events, temporal_events, kg_facts, entities = await asyncio.gather(
            self._search_events_ftx(query, 10),
            self._search_events_temporal(query, 5),
            self._search_kg_by_text(query),
            self._search_entities_by_name(query),
        )

        # RRF fusion for events
        k = 60
        seen_ids = set()
        fused = []
        for rank, ev in enumerate(ftx_events):
            eid = ev.get("id")
            if eid and eid not in seen_ids:
                seen_ids.add(eid)
                ev["_rrf_score"] = 1.0 / (k + rank)
                fused.append(ev)
        for rank, ev in enumerate(temporal_events):
            eid = ev.get("id")
            if eid and eid not in seen_ids:
                seen_ids.add(eid)
                ev["_rrf_score"] = 1.0 / (k + len(ftx_events) + rank)
                fused.append(ev)

        fused.sort(key=lambda x: x.get("_rrf_score", 0), reverse=True)
        for ev in fused:
            ev.pop("_rrf_score", None)

        return {
            "strategy": "hybrid_bm25_vector_temporal",
            "events": _clean_output(fused[:10]),
            "entities": _clean_output(entities),
            "facts": _clean_output(kg_facts),
            "query": query,
        }

    async def _execute_semantic_hybrid(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute semantic hybrid — combines KG facts + vector events + FTX events + entity expansion."""
        budget_tracker.increment_db_calls(4)
        budget_tracker.increment_tokens(len(query) // 3)

        ftx_events, vec_events, kg_facts, entities = await asyncio.gather(
            self._search_events_ftx(query, 10),
            self._search_events_vector(query, 10),
            self._search_kg_by_text(query),
            self._search_entities_by_name(query),
        )

        k = 60
        seen_ids = set()
        fused = []
        for rank, ev in enumerate(ftx_events):
            eid = ev.get("id")
            if eid and eid not in seen_ids:
                seen_ids.add(eid)
                ev["_rrf"] = 1.0 / (k + rank)
                fused.append(ev)
        for rank, ev in enumerate(vec_events):
            eid = ev.get("id")
            if eid not in seen_ids:
                seen_ids.add(eid)
                ev["_rrf"] = 1.0 / (k + len(ftx_events) + rank)
                fused.append(ev)
            elif eid in [x.get("id") for x in fused]:
                for x in fused:
                    if x.get("id") == eid:
                        x["_rrf"] = x.get("_rrf", 0) + 1.0 / (k + rank)
                        break
        fused.sort(key=lambda x: x.get("_rrf", 0), reverse=True)
        fused_events = [x for x in fused[:10]]
        for ev in fused_events:
            ev.pop("_rrf", None)

        seen_entity_ids = {e.get("id") for e in entities if e.get("id")}
        expanded_entities = list(entities)
        seen_fact_ids = {f.get("id") for f in kg_facts if f.get("id")}
        expanded_facts = list(kg_facts)

        words = query.split()
        for w in words:
            w_clean = w.strip(",.!?;:")
            if not w_clean or w_clean[0].islower() or len(w_clean) < 2:
                continue
            more_entities = await self._search_entities_by_name(w_clean)
            for e in more_entities:
                eid = e.get("id")
                if eid and eid not in seen_entity_ids:
                    seen_entity_ids.add(eid)
                    expanded_entities.append(e)
                ename = e.get("name", "")
                if ename:
                    more_facts = await self._search_kg_by_subject(ename)
                    for f in more_facts:
                        fid = f.get("id")
                        if fid and fid not in seen_fact_ids:
                            seen_fact_ids.add(fid)
                            expanded_facts.append(f)

        known_entity_names = {
            e.get("name", "").lower() for e in expanded_entities if e.get("name")
        }

        event_entity_names = set()
        for ev in fused_events + ftx_events:
            content = ev.get("content", "")
            for match in re.finditer(r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)\b", content):
                name = match.group(1).strip()
                if len(name) >= 2:
                    event_entity_names.add(name)

        for name in event_entity_names:
            if name.lower() not in known_entity_names:
                more_entities_found = await self._search_entities_by_name(name)
                for e in more_entities_found:
                    eid = e.get("id")
                    if eid and eid not in seen_entity_ids:
                        seen_entity_ids.add(eid)
                        expanded_entities.append(e)
                    ename = e.get("name", "")
                    if ename:
                        more_facts = await self._search_kg_by_subject(ename)
                        for f in more_facts:
                            fid = f.get("id")
                            if fid and fid not in seen_fact_ids:
                                seen_fact_ids.add(fid)
                                expanded_facts.append(f)

        return {
            "strategy": "semantic_hybrid",
            "events": _clean_output(fused_events),
            "entities": _clean_output(expanded_entities),
            "facts": _clean_output(expanded_facts),
            "query": query,
        }

    async def _execute_hybrid_fallback(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute hybrid fallback strategy — search everything available including temporal fallback."""
        budget_tracker.increment_db_calls(4)
        budget_tracker.increment_tokens(len(query) // 4)

        ftx_events, temporal_events, kg_facts, entities = await asyncio.gather(
            self._search_events_ftx(query, 5),
            self._search_events_temporal(query, 5),
            self._search_kg_by_text(query),
            self._search_entities_by_name(query),
        )

        # RRF fusion for events (FTX + temporal)
        k = 60
        seen_ids = set()
        fused = []
        for rank, ev in enumerate(ftx_events):
            eid = ev.get("id")
            if eid and eid not in seen_ids:
                seen_ids.add(eid)
                ev["_rrf_score"] = 1.0 / (k + rank)
                fused.append(ev)
        for rank, ev in enumerate(temporal_events):
            eid = ev.get("id")
            if eid and eid not in seen_ids:
                seen_ids.add(eid)
                ev["_rrf_score"] = 1.0 / (k + len(ftx_events) + rank)
                fused.append(ev)

        fused.sort(key=lambda x: x.get("_rrf_score", 0), reverse=True)
        for ev in fused:
            ev.pop("_rrf_score", None)

        return {
            "strategy": "hybrid_fallback",
            "events": _clean_output(fused[:10]),
            "entities": _clean_output(entities),
            "facts": _clean_output(kg_facts),
            "query": query,
        }


class PlanExecutor:
    """Executes complete plans using the retrieval executor"""

    def __init__(self):
        self.retrieval_executor = RetrievalExecutor()

    async def execute_plan(
        self, strategy: str, query: str, budget_level: str, **kwargs
    ) -> Dict[str, Any]:
        """
        Execute a complete plan with cost tracking and budget enforcement.
        """
        # Convert string to enum
        strategy_enum = RetrievalStrategy(strategy)
        budget_enum = BudgetLevel(budget_level)

        # Create budget tracker
        budget_tracker = BudgetTracker(budget_enum)

        # Execute the strategy
        result = await self.retrieval_executor.execute_strategy(
            strategy_enum, query, budget_tracker, **kwargs
        )

        # Add execution metadata
        result["execution_metadata"] = {
            "strategy": strategy,
            "budget_level": budget_level,
            "final_db_calls": budget_tracker.db_calls,
            "final_tokens": budget_tracker.estimated_tokens,
            "over_budget": budget_tracker.is_over_budget(),
        }

        return result


# For backward compatibility
async def execute_retrieval_strategy(
    strategy: str, query: str, **kwargs
) -> Dict[str, Any]:
    """Legacy function for executing retrieval strategies."""
    executor = PlanExecutor()
    return await executor.execute_plan(strategy, query, "medium", **kwargs)
