"""
Execution engine for the STRATA Memory Control Plane
Executes the plans generated by the planner using various retrieval strategies
"""

import asyncio
import time
from typing import Dict, List, Any, Optional
from enum import Enum
import logging

# Import the cost tracking functionality
from ..router.policy import QueryType, BudgetLevel
from ..cost_awareness import cost_tracker


class RetrievalStrategy(Enum):
    """Available retrieval strategies"""
    EVENT_LOG_FIRST = "event_log_first"
    KNOWLEDGE_GRAPH_FIRST = "knowledge_graph_first"
    HYBRID_WITH_GRAPH_EXPANSION = "hybrid_with_graph_expansion"
    COMPOSITE_KG_VECTOR = "composite_kg_vector"
    KNOWLEDGE_GRAPH_WITH_INVALIDATION = "knowledge_graph_with_invalidation"
    HYBRID_BM25_VECTOR_TEMPORAL = "hybrid_bm25_vector_temporal"
    HYBRID_FALLBACK = "hybrid_fallback"


class BudgetTracker:
    """Tracks resource consumption for a single execution"""
    
    def __init__(self, budget_level: BudgetLevel):
        self.db_calls = 0
        self.estimated_tokens = 0
        self.budget_level = budget_level
        
        # Budget limits per level
        self.limits = {
            BudgetLevel.LOW: {'db_calls': 10, 'tokens': 1000},
            BudgetLevel.MEDIUM: {'db_calls': 25, 'tokens': 3000},
            BudgetLevel.HIGH: {'db_calls': 50, 'tokens': 8000}
        }
    
    def increment_db_calls(self, count: int = 1):
        self.db_calls += count
    
    def increment_tokens(self, count: int):
        self.estimated_tokens += count
    
    def is_over_budget(self) -> bool:
        limits = self.limits[self.budget_level]
        return (self.db_calls > limits['db_calls'] or 
                self.estimated_tokens > limits['tokens'])
    
    def get_remaining_budget(self) -> Dict[str, int]:
        limits = self.limits[self.budget_level]
        return {
            'remaining_db_calls': max(0, limits['db_calls'] - self.db_calls),
            'remaining_tokens': max(0, limits['tokens'] - self.estimated_tokens)
        }


class RetrievalExecutor:
    """Executes retrieval operations using different strategies"""
    
    def __init__(self):
        self.db_connection = None  # Will be initialized with actual connection
        self.budget_enforcement = True
    
    async def execute_strategy(self, strategy: RetrievalStrategy, query: str, 
                              budget_tracker: BudgetTracker, **kwargs) -> Dict[str, Any]:
        """
        Execute a retrieval strategy with budget enforcement and cost tracking.
        """
        start_time = time.time()
        success = True
        num_queries = 0
        relevance_score = 0.5  # Default relevance until actual results are evaluated
        
        try:
            if budget_tracker.is_over_budget():
                raise Exception("Over budget")
            
            # Execute the specific strategy
            if strategy == RetrievalStrategy.EVENT_LOG_FIRST:
                result = await self._execute_event_log_first(query, budget_tracker, **kwargs)
                num_queries += 1
            elif strategy == RetrievalStrategy.KNOWLEDGE_GRAPH_FIRST:
                result = await self._execute_knowledge_graph_first(query, budget_tracker, **kwargs)
                num_queries += 1
            elif strategy == RetrievalStrategy.HYBRID_WITH_GRAPH_EXPANSION:
                result = await self._execute_hybrid_with_graph_expansion(query, budget_tracker, **kwargs)
                num_queries += 2  # More complex query
            elif strategy == RetrievalStrategy.COMPOSITE_KG_VECTOR:
                result = await self._execute_composite_kg_vector(query, budget_tracker, **kwargs)
                num_queries += 2
            elif strategy == RetrievalStrategy.KNOWLEDGE_GRAPH_WITH_INVALIDATION:
                result = await self._execute_knowledge_graph_with_invalidation(query, budget_tracker, **kwargs)
                num_queries += 2  # Includes write operations
            elif strategy == RetrievalStrategy.HYBRID_BM25_VECTOR_TEMPORAL:
                result = await self._execute_hybrid_bm25_vector_temporal(query, budget_tracker, **kwargs)
                num_queries += 2
            elif strategy == RetrievalStrategy.HYBRID_FALLBACK:
                result = await self._execute_hybrid_fallback(query, budget_tracker, **kwargs)
                num_queries += 1
            else:
                raise ValueError(f"Unknown strategy: {strategy}")
            
            # Calculate relevance based on result quality
            relevance_score = self._calculate_relevance_score(result, query)
            
        except Exception as e:
            success = False
            logging.error(f"Strategy {strategy.value} failed: {e}")
            result = {"error": str(e), "results": []}
        
        finally:
            # Record metrics regardless of success/failure
            end_time = time.time()
            latency = end_time - start_time
            
            # Record the request with actual performance metrics
            cost_tracker.record_request(
                strategy=strategy.value,
                latency=latency,
                success=success,
                num_queries=num_queries,
                relevance=relevance_score
            )
        
        return result
    
    def _calculate_relevance_score(self, result: Dict[str, Any], query: str) -> float:
        """Calculate a relevance score based on the result quality."""
        # Simple heuristic for relevance calculation
        if "error" in result:
            return 0.1
        
        # Count the number of meaningful results
        results = result.get("results", [])
        if not results:
            return 0.2
        
        # More results generally mean higher relevance, but cap it
        result_count = len(results)
        relevance = min(0.9, 0.3 + (result_count * 0.1))
        
        # Boost for specific query types if results match expectations
        query_lower = query.lower()
        if any(word in query_lower for word in ["who", "what", "where"]) and result_count > 0:
            relevance = min(1.0, relevance + 0.1)
        
        return relevance
    
    async def _execute_event_log_first(self, query: str, budget_tracker: BudgetTracker, **kwargs) -> Dict[str, Any]:
        """Execute event log first strategy."""
        # Simulate database calls
        budget_tracker.increment_db_calls(1)
        budget_tracker.increment_tokens(len(query) // 4)  # Rough token estimation
        
        # Actual implementation would go here
        # For now, simulate the operation
        await asyncio.sleep(0.1)  # Simulate I/O delay
        
        return {
            "strategy": "event_log_first",
            "results": [{"type": "event", "content": f"Event result for: {query}", "id": "event:123"}],
            "query": query
        }
    
    async def _execute_knowledge_graph_first(self, query: str, budget_tracker: BudgetTracker, **kwargs) -> Dict[str, Any]:
        """Execute knowledge graph first strategy."""
        budget_tracker.increment_db_calls(1)
        budget_tracker.increment_tokens(len(query) // 4)
        
        await asyncio.sleep(0.15)  # Simulate I/O delay
        
        return {
            "strategy": "knowledge_graph_first",
            "results": [{"type": "entity", "name": query, "relations": []}],
            "query": query
        }
    
    async def _execute_hybrid_with_graph_expansion(self, query: str, budget_tracker: BudgetTracker, **kwargs) -> Dict[str, Any]:
        """Execute hybrid with graph expansion strategy."""
        budget_tracker.increment_db_calls(2)
        budget_tracker.increment_tokens(len(query) // 3)  # Higher token usage due to expansion
        
        await asyncio.sleep(0.25)  # More complex operation
        
        return {
            "strategy": "hybrid_with_graph_expansion",
            "results": [
                {"type": "entity", "name": query, "relations": ["expanded"]},
                {"type": "event", "content": f"Related to {query}", "id": "event:456"}
            ],
            "query": query
        }
    
    async def _execute_composite_kg_vector(self, query: str, budget_tracker: BudgetTracker, **kwargs) -> Dict[str, Any]:
        """Execute composite KG-vector strategy."""
        budget_tracker.increment_db_calls(2)
        budget_tracker.increment_tokens(len(query) // 3)
        
        await asyncio.sleep(0.2)
        
        return {
            "strategy": "composite_kg_vector",
            "results": [{"type": "combined", "content": f"Combined result for: {query}"}],
            "query": query
        }
    
    async def _execute_knowledge_graph_with_invalidation(self, query: str, budget_tracker: BudgetTracker, **kwargs) -> Dict[str, Any]:
        """Execute knowledge graph with invalidation strategy."""
        budget_tracker.increment_db_calls(2)  # Includes write operations
        budget_tracker.increment_tokens(len(query) // 4)
        
        await asyncio.sleep(0.3)  # Invalidation is more expensive
        
        return {
            "strategy": "knowledge_graph_with_invalidation",
            "results": [{"type": "updated", "content": f"Updated knowledge for: {query}"}],
            "query": query
        }
    
    async def _execute_hybrid_bm25_vector_temporal(self, query: str, budget_tracker: BudgetTracker, **kwargs) -> Dict[str, Any]:
        """Execute hybrid BM25-vector-temporal strategy."""
        budget_tracker.increment_db_calls(2)
        budget_tracker.increment_tokens(len(query) // 3)
        
        await asyncio.sleep(0.2)
        
        return {
            "strategy": "hybrid_bm25_vector_temporal",
            "results": [{"type": "hybrid", "content": f"Hybrid result for: {query}"}],
            "query": query
        }
    
    async def _execute_hybrid_fallback(self, query: str, budget_tracker: BudgetTracker, **kwargs) -> Dict[str, Any]:
        """Execute hybrid fallback strategy."""
        budget_tracker.increment_db_calls(1)
        budget_tracker.increment_tokens(len(query) // 4)
        
        await asyncio.sleep(0.1)
        
        return {
            "strategy": "hybrid_fallback",
            "results": [{"type": "fallback", "content": f"Fallback result for: {query}"}],
            "query": query
        }


class PlanExecutor:
    """Executes complete plans using the retrieval executor"""
    
    def __init__(self):
        self.retrieval_executor = RetrievalExecutor()
    
    async def execute_plan(self, strategy: str, query: str, budget_level: str, **kwargs) -> Dict[str, Any]:
        """
        Execute a complete plan with cost tracking and budget enforcement.
        """
        # Convert string to enum
        strategy_enum = RetrievalStrategy(strategy)
        budget_enum = BudgetLevel(budget_level)
        
        # Create budget tracker
        budget_tracker = BudgetTracker(budget_enum)
        
        # Execute the strategy
        result = await self.retrieval_executor.execute_strategy(
            strategy_enum, query, budget_tracker, **kwargs
        )
        
        # Add execution metadata
        result["execution_metadata"] = {
            "strategy": strategy,
            "budget_level": budget_level,
            "final_db_calls": budget_tracker.db_calls,
            "final_tokens": budget_tracker.estimated_tokens,
            "over_budget": budget_tracker.is_over_budget()
        }
        
        return result


# For backward compatibility
async def execute_retrieval_strategy(strategy: str, query: str, **kwargs) -> Dict[str, Any]:
    """Legacy function for executing retrieval strategies."""
    executor = PlanExecutor()
    return await executor.execute_plan(strategy, query, "medium", **kwargs)